function FullFinData_x = makefinData_x(Dataset)
% Makes a x-cordinate matix for obtaining raw data
FullFinData_x = [Dataset.fin1_x, Dataset.fin2_x, Dataset.fin3_x, Dataset.fin4_x, Dataset.fin5_x, Dataset.fin6_x, Dataset.fin7_x,...
    Dataset.fin8_x, Dataset.fin9_x, Dataset.fin10_x, Dataset.fin11_x, Dataset.fin12_x, Dataset.fin13_x, Dataset.fin14_x, Dataset.fin15_x...
    Dataset.fin16_x, Dataset.fin17_x, Dataset.fin18_x, Dataset.fin19_x, Dataset.fin20_x, Dataset.fin21_x, Dataset.fin22_x, Dataset.fin23_x...
    Dataset.fin24_x, Dataset.fin25_x, Dataset.fin26_x, Dataset.fin27_x, Dataset.fin28_x, Dataset.fin29_x, Dataset.fin30_x, Dataset.fin31_x...
    Dataset.fin32_x, Dataset.fin33_x, Dataset.fin34_x];


end