function FullFinData_y = makefinData_y(Dataset)
% Makes a y-cordinate matix for obtaining raw data
FullFinData_y = [Dataset.fin1_y, Dataset.fin2_y, Dataset.fin3_y, Dataset.fin4_y, Dataset.fin5_y, Dataset.fin6_y, Dataset.fin7_y,...
    Dataset.fin8_y, Dataset.fin9_y, Dataset.fin10_y, Dataset.fin11_y, Dataset.fin12_y, Dataset.fin13_y, Dataset.fin14_y, Dataset.fin15_y...
    Dataset.fin16_y, Dataset.fin17_y, Dataset.fin18_y, Dataset.fin19_y, Dataset.fin20_y, Dataset.fin21_y, Dataset.fin22_y, Dataset.fin23_y...
    Dataset.fin24_y, Dataset.fin25_y, Dataset.fin26_y, Dataset.fin27_y, Dataset.fin28_y, Dataset.fin29_y, Dataset.fin30_y, Dataset.fin31_y...
    Dataset.fin32_y, Dataset.fin33_y, Dataset.fin34_y];

end